### ISSUE TITLE
Implement `signInAnonymously` from the JS client

### ISSUE THREAD

**Issue by acupofjose** [supabase-community/gotrue-csharp#88]
Re: https://github.com/supabase-community/gotrue-csharp/discussions/87

Current Supabase Documentation:
https://supabase.com/docs/guides/auth/auth-anonymous

Relevant Code here:
https://github.com/supabase/auth-js/blob/92fefbd49f25e20793ca74d5b83142a1bb805a18/src/GoTrueClient.ts#L368-L401

**Comment by acupofjose** [comment]
Available in v4.2.7

**Comment by kaushalkumar86** [comment]
Thanks for the instant update.
I already implemented it and its working as expected.
Although, I have a few more requests, **can you please add the following lines in User.cs**, so that it can be checked whether the user is anonymous or not..

`[JsonProperty("is_anonymous")]
public bool IsAnomynous { get; set; }`

Also, can you also look into supabase.auth.linkIdentity, referenced https://github.com/supabase/auth-js/blob/92fefbd49f25e20793ca74d5b83142a1bb805a18/src/GoTrueClient.ts#L1734-L1799

**Comment by acupofjose** [comment]
Can do!

**Comment by acupofjose** [comment]
Available in v4.3.0
